from __future__ import annotations
import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER

EXPORT_DIR = Path("exports")
EXPORT_DIR.mkdir(exist_ok=True)

PRIMARY   = colors.HexColor("#1a6b9a")
SECONDARY = colors.HexColor("#2ecc71")
LIGHT_BG  = colors.HexColor("#f0f4f8")
TEXT      = colors.HexColor("#2d3748")
MUTED     = colors.HexColor("#718096")

def generate_report(chat_history: List[Dict[str, str]], session_summary: str = "", filename: str = "") -> str:
    if not filename:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"medical_report_{ts}.pdf"
    output_path = EXPORT_DIR / filename
    base = getSampleStyleSheet()
    title_s  = ParagraphStyle("T", parent=base["Title"], textColor=PRIMARY, fontSize=22, spaceAfter=4, alignment=TA_CENTER)
    sub_s    = ParagraphStyle("S", parent=base["Normal"], textColor=MUTED, fontSize=10, spaceAfter=16, alignment=TA_CENTER)
    sec_s    = ParagraphStyle("H", parent=base["Heading2"], textColor=PRIMARY, fontSize=13, spaceBefore=14, spaceAfter=4)
    user_s   = ParagraphStyle("U", parent=base["Normal"], textColor=SECONDARY, fontSize=9, fontName="Helvetica-Bold", spaceAfter=2)
    agent_s  = ParagraphStyle("A", parent=base["Normal"], textColor=PRIMARY, fontSize=9, fontName="Helvetica-Bold", spaceAfter=2)
    body_s   = ParagraphStyle("B", parent=base["Normal"], textColor=TEXT, fontSize=10, leading=15, spaceAfter=10)
    footer_s = ParagraphStyle("F", parent=base["Normal"], textColor=MUTED, fontSize=8, alignment=TA_CENTER)
    doc = SimpleDocTemplate(str(output_path), pagesize=A4, leftMargin=2.5*cm, rightMargin=2.5*cm, topMargin=2.5*cm, bottomMargin=2.5*cm)
    story = []
    story.append(Paragraph("Medical Agent Session Report", title_s))
    story.append(Paragraph(datetime.now().strftime("%B %d, %Y  %H:%M"), sub_s))
    story.append(HRFlowable(width="100%", thickness=1.5, color=PRIMARY, spaceAfter=14))
    if session_summary:
        story.append(Paragraph("Session Summary", sec_s))
        story.append(Paragraph(session_summary, body_s))
    story.append(Paragraph("Conversation Log", sec_s))
    story.append(Spacer(1, 6))
    for i, msg in enumerate(chat_history, 1):
        role    = msg.get("role", "unknown")
        content = msg.get("content", "").strip()
        if not content:
            continue
        label = f"You (turn {i})" if role == "user" else f"Agent (turn {i})"
        style = user_s if role == "user" else agent_s
        story.append(Paragraph(label, style))
        cell = Paragraph(content.replace("\n", "<br/>"), body_s)
        bg   = LIGHT_BG if role == "user" else colors.white
        tbl  = Table([[cell]], colWidths=[14.5*cm])
        tbl.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),bg),("BOX",(0,0),(-1,-1),0.5,colors.HexColor("#cbd5e0")),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8),("LEFTPADDING",(0,0),(-1,-1),10),("RIGHTPADDING",(0,0),(-1,-1),10)]))
        story.append(tbl)
        story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MUTED, spaceBefore=16))
    story.append(Paragraph("This report is generated by an AI agent for informational purposes only. Not a substitute for professional medical advice.", footer_s))
    doc.build(story)
    return str(output_path.resolve())
